name: Deploy

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build production
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
